### PR TITLE
Fixed JSDoc comments

### LINKED ISSUE #2079: Fix JSDoc comments
Currently, the JSDoc comments have an incorrect syntax, which is causing NetBeans to show me loads of warnings.

As an example, we have something like

    @param  object die      The die whose recipe is to be displayed

This should actually be

    @param  {object} die      The die whose recipe is to be displayed

See http://usejsdoc.org/tags-param.html

Also

    @return  object

should actually be

    @returns  {object}

See http://usejsdoc.org/tags-returns.html

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2079.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1202/ (if it passes)

### CODE REVIEW

File: src/ui/js/Game.js [hunk 1]
```diff
@@ -2699,11 +2699,11 @@ Game.gamePlayerStatus = function(player, reversed, game_active) {
...
- * @param  object  die            The die to be displayed
- * @param  boolean die_status     Status of the die ('active' or 'captured')
- * @param  string  player         Whose is the die? ('player' or 'opponent')
- * @param  boolean player_active  Is the player displaying the die active?
- * @return object
+ * @param  {object}  die            The die to be displayed
+ * @param  {boolean} die_status     Status of the die ('active' or 'captured')
+ * @param  {string}  player         Whose is the die? ('player' or 'opponent')
+ * @param  {boolean} player_active  Is the player displaying the die active?
+ * @returns {object}
```
Comment (cgolubi1) [inline src/ui/js/Game.js]: This is nit-level, but there were previously two spaces after each param so that the param types would line up with the return types.  Can you add a third space after each param so they line up with the 'returns' types?

File: src/ui/js/Game.js [hunk 2]
```diff
@@ -3019,10 +3020,10 @@ Game.createDieContainerDiv = function(
  * Return a game-mat-style display of all dice belonging to the
  * requested player
  *
- * @param  string  player        Whose dice to display ('player' or 'opponent')
- * @param  boolean player_active Is the game awaiting action from the player
- *                               who is loading the page?
- * @return object                jQuery containing the div of dice
+ * @param  {string}  player        Whose dice to display ('player' / 'opponent')
```
Comment (cgolubi1) [inline src/ui/js/Game.js]: Hmm.  What's wrong with "or"?

Comment (blackshadowshade) [inline src/ui/js/Game.js]: I'm running up against the 80 character limit here. Would you prefer 'or' with less aligned spacing or the '|' symbol?

File: src/ui/js/Game.js (hunk 1 above)
Comment (blackshadowshade) [inline src/ui/js/Game.js]: Here, I can add a third space, but in later comments, I start running up against the 80 character limit.

**Comment by blackshadowshade** [comment]
Okay, I've prioritised alignment and shortened some lines by using the '|' symbol to stay within the 80 character limit.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1206/ (if it passes)

**Comment by cgolubi1** [comment]
Yeah, sorry, i forgot the spacing was going to bite you.  Probably we should deprioritize alignment or normalize line-wrapping, but this is fine for now.
