### PR TITLE
Fixed logic when checking if an attack needs fire support

### LINKED ISSUE #1714: Skill Attack allowed even though attacking total doesn't equal defending value
In http://dev.buttonweavers.com/ui/game.html?game=1844, Devious and I each made an attack that should have been illegal:

> Devious performed Skill attack using [m(5):3,k(8):8,d(Y=8):5] against [d(Y=1):1]; Defender d(Y=1) was captured; Attacker m(5) changed size from 5 to 1 sides, recipe changed from m(5) to m(Y=1), rerolled 3 => 1; Attacker k(8) does not reroll; Attacker d(Y=8) rerolled 5 => 3

3 + 5 + k8 can't equal 1, whether the k8 adds or subtracts.

> irilyth performed Skill attack using [n(4):3,m(5):3,k(8):7] against [m(Y=1):1]; Defender m(Y=1) recipe changed to mn(Y=1), was captured; Attacker n(4) rerolled 3 => 4; Attacker m(5) changed size from 5 to 1 sides, recipe changed from m(5) to m(Y=1), rerolled 3 => 1; Attacker k(8) does not reroll

Similarly, 3 + 3 + k7 doesn't equal 1.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1714.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/878/

### CODE REVIEW

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/891/

**Comment by cgolubi1** [comment]
Hmm... should we really have pushed to prod without this fix?  I'm afraid i lost track of things, though in my defense everyone else did too.  :>(

**Comment by cgolubi1** [comment]
Ah, right, never mind --- it's a Konstant/Fire interaction bug.  And on prod there are no buttons with both Konstant and Fire, and RandomBMMixed excludes Fire.  So we're okay.

File: test/src/api/responderTest.php [hunk 1]
```diff
@@ -11972,6 +11972,95 @@ public function test_interface_game_040() {
...
+            'responder003 chose to perform a Skill attack using [k(8):3,d(Y=18):4] against [(20):4]; responder003 must turn down fire dice to complete this attack. ',
+            $retval, array(array(0, 2), array(0, 4), array(1, 0)),
+            $gameId, 1, 'Skill', 0, 1, '');
+
+        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 chose to perform a Skill attack using [k(8):3,d(Y=18):4] against [(20):4]; responder003 must turn down fire dice to complete this attack'));
+        $expData['gameActionLogCount'] += 1;
+        $expData['gameState'] = 'ADJUST_FIRE_DICE';
+        $expData['validAttackTypeArray'] = array('Skill');
+        $expData['playerDataArray'][0]['activeDieArray'][2]['properties'] = array('IsAttacker');
+        $expData['playerDataArray'][0]['activeDieArray'][4]['properties'] = array('IsAttacker');
```
Comment (cgolubi1) [inline test/src/api/responderTest.php]: You accidentally removed the:
```php
$retval = $this->verify_api_loadGameData($expData, $gameId, 10);
```

from this test, so the end of it is not actually doing anything.

**Comment by cgolubi1** [comment]
Otherwise... this modifies the operation of `needs_firing()` to use a fairly different logic path, probably a cleaner one, but every attack type implements `validate_attack()`, so it's pretty different.  I want to:
* throw a lot of regression checks against this (both with and without Fire dice), maybe thousands to try to get some corner cases
* play a bunch of new randomAI games against this (again both with and without Fire, though maybe more with than without)
* play some manual games with various types of invalid attacks to see if i can break it

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/904/

**Comment by cgolubi1** [comment]
So there is a konstant/Fire UI bug:
konstant_fire_ui_bug

**Comment by cgolubi1** [comment]
Okay.  Should this attack be legal?  Inquiring minds want to know:
should_this_attack_be_legal

At the moment, it is not, if that affects anyone's thinking.  And i think that's probably reasonable.  But i figured i'd check.

**Comment by cgolubi1** [comment]
Okay, so in the last visible turn of this rather long game, Hawaii makes the first half of the attack in the first screencap, which we concluded on IRC should not be legal.  When i have time, i'll trim this down and make an example where the activity takes place in the first round:
```php
    public function test_interface_game_00001() {

        // responder003 is the POV player, so if you need to fake
        // login as a different player e.g. to submit an attack, always
        // return to responder003 as soon as you've done so
        $this->game_number = 1;
        $_SESSION = $this->mock_test_user_login('responder003');


        $gameId = $this->verify_api_createGame(
            array(4, 5, 1, 4, 20, 14, 12),
            'responder003', 'responder004', 'Hawaii', 'Vincent', 3
        );

        $expData = $this->squash_game_data_timestamps(json_decode('{"previousGameId": null, "gameChatEditable": false, "gameId": 199, "description": "", "timestamp": 1447209244, "gameChatLog": [], "roundNumber": 1, "playerWithInitiativeIdx": null, "gameActionLogCount": 0, "gameState": "SPECIFY_DICE", "validAttackTypeArray": [], "activePlayerIdx": null, "gameSkillsInfo": {"Fire": {"code": "F", "interacts": [], "description": "Fire Dice cannot make Power Attacks. Instead, they can assist other Dice in making Skill and Power Attacks. Before making a Skill or Power Attack, you may increase the value showing on any of the attacking dice, and decrease the values showing on one or more of your Fire Dice by the same amount. For example, if you wish to increase the value of an attacking die by 5 points, you can take 5 points away from one or more of your Fire Dice. Turn the Fire Dice to show the adjusted values, and then make the attack as normal. Dice can never be increased or decreased outside their normal range, i.e., a 10-sided die can never show a number lower than 1 or higher than 10. Also, Fire Dice cannot assist other dice in making attacks other than normal Skill and Power Attacks."}, "Stealth": {"code": "d", "interacts": [], "description": "These dice cannot perform any type of attack other than Multi-die Skill Attacks, meaning two or more dice participating in a Skill Attack. In addition, Stealth Dice cannot be captured by any attack other than a Multi-die Skill Attack."}, "Null": {"code": "n", "interacts": [], "description": "When a Null Die participates in any attack, the dice that are captured are worth zero points. Null Dice themselves are worth zero points."}, "Konstant": {"code": "k", "interacts": [], "description": "These dice do not reroll after an attack; they keep their current value. Konstant dice can not Power Attack, and cannot perform a Skill Attack by themselves, but they can add OR subtract their value in a multi-dice Skill Attack. If another skill causes a Konstant die to reroll (e.g., Chance, Trip, Ornery), it continues to show the same value. If another skill causes the die to change its value without rerolling (e.g., Focus, Fire), the die\'s value does change and then continues to show that new value."}, "Morphing": {"code": "m", "interacts": [], "description": "When a Morphing Die is used in any attack, it changes size, becoming the same size as the die that was captured. It is then re-rolled. Morphing Dice change size every time they capture another die. If a Morphing die is captured, its scoring value is based on its size at the time of capture; likewise, if it is not captured during a round, its scoring value is based on its size at the end of the round"}}, "gameActionLog": [], "maxWins": 3, "playerDataArray": [{"prevOptValueArray": [], "optRequestArray": [], "playerColor": "#dd99dd", "roundScore": null, "waitingOnAction": true, "playerId": 4, "outOfPlayDieArray": [], "button": {"artFilename": "BMdefaultRound.png", "recipe": "n(4) m(5) k(8) F(13) d(Y)", "name": "Hawaii"}, "capturedDieArray": [], "activeDieArray": [{"description": "Null 4-sided die", "skills": ["Null"], "recipe": "n(4)", "value": null, "properties": [], "sides": 4}, {"description": "Morphing 5-sided die", "skills": ["Morphing"], "recipe": "m(5)", "value": null, "properties": [], "sides": 5}, {"description": "Konstant 8-sided die", "skills": ["Konstant"], "recipe": "k(8)", "value": null, "properties": [], "sides": 8}, {"description": "Fire 13-sided die", "skills": ["Fire"], "recipe": "F(13)", "value": null, "properties": [], "sides": 13}, {"description": "Stealth Y Swing Die", "skills": ["Stealth"], "recipe": "d(Y)", "value": null, "properties": [], "sides": null}], "canStillWin": null, "swingRequestArray": {"Y": [1, 20]}, "hasDismissedGame": false, "gameScoreArray": {"L": 0, "W": 0, "D": 0}, "sideScore": null, "playerName": "responder003", "prevSwingValueArray": [], "lastActionTime": 1447209244}, {"prevOptValueArray": [], "optRequestArray": {"3": ["6", "30"]}, "playerColor": "#ddffdd", "roundScore": null, "waitingOnAction": true, "playerId": 5, "outOfPlayDieArray": [], "button": {"artFilename": "vincent.png", "recipe": "(30) (30) (30) (6/30)", "name": "Vincent"}, "capturedDieArray": [], "activeDieArray": [{"description": "30-sided die", "skills": [], "recipe": "(30)", "value": null, "properties": [], "sides": 30}, {"description": "30-sided die", "skills": [], "recipe": "(30)", "value": null, "properties": [], "sides": 30}, {"description": "30-sided die", "skills": [], "recipe": "(30)", "value": null, "properties": [], "sides": 30}, {"description": "Option Die (with 6 or 30 sides)", "skills": [], "recipe": "(6/30)", "value": null, "properties": [], "sides": null}], "canStillWin": null, "swingRequestArray": [], "hasDismissedGame": false, "gameScoreArray": {"L": 0, "W": 0, "D": 0}, "sideScore": null, "playerName": "responder004", "prevSwingValueArray": [], "lastActionTime": 1447209244}], "gameChatLogCount": 0, "currentPlayerIdx": 0}', TRUE));
        $expData['gameId'] = $gameId;
        $expData['playerDataArray'][0]['playerId'] = $this->user_ids['responder003'];
        $expData['playerDataArray'][1]['playerId'] = $this->user_ids['responder004'];

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_submitDieValues(
            array(3),
            $gameId, 1, array('Y' => 3), NULL);

        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 set die sizes'));
        $expData['gameActionLogCount'] = 1;
        $expData['playerDataArray'][0]['activeDieArray'][4]['description'] = "Stealth Y Swing Die (with 3 sides)";
        $expData['playerDataArray'][0]['activeDieArray'][4]['sides'] = 3;
        $expData['playerDataArray'][0]['waitingOnAction'] = false;

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $_SESSION = $this->mock_test_user_login('responder004');
        $this->verify_api_submitDieValues(
            array(15),
            $gameId, 1, NULL, array(3 => 30));
        $_SESSION = $this->mock_test_user_login('responder003');

        $expData['activePlayerIdx'] = 0;
        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 set swing values: Y=3'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder004', 'message' => 'responder004 set option dice: (6/30=30)'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => '', 'message' => 'responder003 won initiative for round 1. Initial die values: responder003 rolled [n(4):4, m(5):5, k(8):1, F(13):4, d(Y=3):3], responder004 rolled [(30):20, (30):14, (30):12, (6/30=30):15].'));
        $expData['gameActionLogCount'] = 3;
        $expData['gameState'] = "START_TURN";
        $expData['playerDataArray'][0]['activeDieArray'][0]['value'] = 4;
        $expData['playerDataArray'][0]['activeDieArray'][1]['value'] = 5;
        $expData['playerDataArray'][0]['activeDieArray'][2]['value'] = 1;
        $expData['playerDataArray'][0]['activeDieArray'][3]['value'] = 4;
        $expData['playerDataArray'][0]['activeDieArray'][4]['value'] = 3;
        $expData['playerDataArray'][0]['roundScore'] = 14.5;
        $expData['playerDataArray'][0]['sideScore'] = -30.3;
        $expData['playerDataArray'][0]['waitingOnAction'] = true;
        $expData['playerDataArray'][1]['activeDieArray'][0]['value'] = 20;
        $expData['playerDataArray'][1]['activeDieArray'][1]['value'] = 14;
        $expData['playerDataArray'][1]['activeDieArray'][2]['value'] = 12;
        $expData['playerDataArray'][1]['activeDieArray'][3]['description'] = "Option Die (with 30 sides)";
        $expData['playerDataArray'][1]['activeDieArray'][3]['sides'] = 30;
        $expData['playerDataArray'][1]['activeDieArray'][3]['value'] = 15;
        $expData['playerDataArray'][1]['roundScore'] = 60;
        $expData['playerDataArray'][1]['sideScore'] = 30.3;
        $expData['playerDataArray'][1]['waitingOnAction'] = false;
        $expData['playerWithInitiativeIdx'] = 0;
        $expData['validAttackTypeArray'] = array("Skill");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_submitTurn(
            array(4, 25, 1, 2),
            'responder003 performed Skill attack using [n(4):4,m(5):5,k(8):1,F(13):4,d(Y=3):3] against [(6/30=30):15]; Defender (6/30=30) recipe changed to n(6/30=30), was captured; Attacker n(4) rerolled 4 => 4; Attacker m(5) changed size from 5 to 30 sides, recipe changed from m(5) to m(6/30=30), rerolled 5 => 25; Attacker k(8) does not reroll; Attacker F(13) rerolled 4 => 1; Attacker d(Y=3) rerolled 3 => 2. ',
            $retval, array(array(0, 0), array(0, 1), array(0, 2), array(0, 3), array(0, 4), array(1, 3)),
            $gameId, 1, 'Skill', 0, 1, '');

        $expData['activePlayerIdx'] = 1;
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 performed Skill attack using [n(4):4,m(5):5,k(8):1,F(13):4,d(Y=3):3] against [(6/30=30):15]; Defender (6/30=30) recipe changed to n(6/30=30), was captured; Attacker n(4) rerolled 4 => 4; Attacker m(5) changed size from 5 to 30 sides, recipe changed from m(5) to m(6/30=30), rerolled 5 => 25; Attacker k(8) does not reroll; Attacker F(13) rerolled 4 => 1; Attacker d(Y=3) rerolled 3 => 2'));
        $expData['gameActionLogCount'] = 4;
        $expData['playerDataArray'][0]['activeDieArray'][1]['description'] = "Morphing Option Die (with 30 sides)";
        $expData['playerDataArray'][0]['activeDieArray'][1]['properties'] = array("HasJustMorphed");
        $expData['playerDataArray'][0]['activeDieArray'][1]['recipe'] = "m(6/30)";
        $expData['playerDataArray'][0]['activeDieArray'][1]['sides'] = 30;
        $expData['playerDataArray'][0]['activeDieArray'][1]['value'] = 25;
        $expData['playerDataArray'][0]['activeDieArray'][3]['value'] = 1;
        $expData['playerDataArray'][0]['activeDieArray'][4]['value'] = 2;
        $expData['playerDataArray'][0]['capturedDieArray'][0]['properties'] = array("WasJustCaptured");
        $expData['playerDataArray'][0]['capturedDieArray'][0]['recipe'] = "n(6/30)";
        $expData['playerDataArray'][0]['capturedDieArray'][0]['sides'] = 30;
        $expData['playerDataArray'][0]['capturedDieArray'][0]['value'] = 15;
        $expData['playerDataArray'][0]['optRequestArray'] = array("1" => array(6, 30));
        $expData['playerDataArray'][0]['roundScore'] = 27;
        $expData['playerDataArray'][0]['sideScore'] = -12;
        $expData['playerDataArray'][0]['waitingOnAction'] = false;
        array_pop($expData['playerDataArray'][1]['activeDieArray']);
        $expData['playerDataArray'][1]['optRequestArray'] = array();
        $expData['playerDataArray'][1]['roundScore'] = 45;
        $expData['playerDataArray'][1]['sideScore'] = 12;
        $expData['playerDataArray'][1]['waitingOnAction'] = true;
        $expData['validAttackTypeArray'] = array("Power");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $_SESSION = $this->mock_test_user_login('responder004');
        $this->verify_api_submitTurn(
            array(26),
            'responder004 performed Power attack using [(30):14] against [n(4):4]; Defender n(4) was captured; Attacker (30) rerolled 14 => 26. ',
            $retval, array(array(1, 1), array(0, 0)),
            $gameId, 1, 'Power', 1, 0, '');
        $_SESSION = $this->mock_test_user_login('responder003');

        $expData['activePlayerIdx'] = 0;
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder004', 'message' => 'responder004 performed Power attack using [(30):14] against [n(4):4]; Defender n(4) was captured; Attacker (30) rerolled 14 => 26'));
        $expData['gameActionLogCount'] = 5;
        $expData['playerDataArray'][0]['activeDieArray'][0]['description'] = "Morphing Option Die (with 30 sides)";
        $expData['playerDataArray'][0]['activeDieArray'][0]['recipe'] = "m(6/30)";
        $expData['playerDataArray'][0]['activeDieArray'][0]['sides'] = 30;
        $expData['playerDataArray'][0]['activeDieArray'][0]['skills'] = array("Morphing");
        $expData['playerDataArray'][0]['activeDieArray'][0]['value'] = 25;
        $expData['playerDataArray'][0]['activeDieArray'][1]['description'] = "Konstant 8-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][1]['properties'] = array();
        $expData['playerDataArray'][0]['activeDieArray'][1]['recipe'] = "k(8)";
        $expData['playerDataArray'][0]['activeDieArray'][1]['sides'] = 8;
        $expData['playerDataArray'][0]['activeDieArray'][1]['skills'] = array("Konstant");
        $expData['playerDataArray'][0]['activeDieArray'][1]['value'] = 1;
        $expData['playerDataArray'][0]['activeDieArray'][2]['description'] = "Fire 13-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][2]['recipe'] = "F(13)";
        $expData['playerDataArray'][0]['activeDieArray'][2]['sides'] = 13;
        $expData['playerDataArray'][0]['activeDieArray'][2]['skills'] = array("Fire");
        $expData['playerDataArray'][0]['activeDieArray'][3]['description'] = "Stealth Y Swing Die (with 3 sides)";
        $expData['playerDataArray'][0]['activeDieArray'][3]['recipe'] = "d(Y)";
        $expData['playerDataArray'][0]['activeDieArray'][3]['sides'] = 3;
        $expData['playerDataArray'][0]['activeDieArray'][3]['skills'] = array("Stealth");
        $expData['playerDataArray'][0]['activeDieArray'][3]['value'] = 2;
        array_pop($expData['playerDataArray'][0]['activeDieArray']);
        $expData['playerDataArray'][0]['capturedDieArray'][0]['properties'] = array();
        $expData['playerDataArray'][0]['optRequestArray'] = array(array(6, 30));
        $expData['playerDataArray'][0]['waitingOnAction'] = true;
        $expData['playerDataArray'][1]['activeDieArray'][1]['value'] = 26;
        $expData['playerDataArray'][1]['capturedDieArray'][0]['properties'] = array("WasJustCaptured");
        $expData['playerDataArray'][1]['capturedDieArray'][0]['recipe'] = "n(4)";
        $expData['playerDataArray'][1]['capturedDieArray'][0]['sides'] = 4;
        $expData['playerDataArray'][1]['capturedDieArray'][0]['value'] = 4;
        $expData['playerDataArray'][1]['waitingOnAction'] = false;
        $expData['validAttackTypeArray'] = array("Power", "Skill");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_submitTurn(
            array(28, 1),
            'responder003 performed Skill attack using [m(6/30=30):25,k(8):1,d(Y=3):2] against [(30):26]; Defender (30) was captured; Attacker m(6/30=30) remained the same size, recipe changed from m(6/30=30) to m(30), rerolled 25 => 28; Attacker k(8) does not reroll; Attacker d(Y=3) rerolled 2 => 1. ',
            $retval, array(array(0, 0), array(0, 1), array(0, 3), array(1, 1)),
            $gameId, 1, 'Skill', 0, 1, '');

        $expData['activePlayerIdx'] = 1;
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 performed Skill attack using [m(6/30=30):25,k(8):1,d(Y=3):2] against [(30):26]; Defender (30) was captured; Attacker m(6/30=30) remained the same size, recipe changed from m(6/30=30) to m(30), rerolled 25 => 28; Attacker k(8) does not reroll; Attacker d(Y=3) rerolled 2 => 1'));
        $expData['gameActionLogCount'] = 6;
        $expData['playerDataArray'][0]['activeDieArray'][0]['description'] = "Morphing 30-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array("HasJustMorphed");
        $expData['playerDataArray'][0]['activeDieArray'][0]['recipe'] = "m(30)";
        $expData['playerDataArray'][0]['activeDieArray'][0]['value'] = 28;
        $expData['playerDataArray'][0]['activeDieArray'][3]['value'] = 1;
        $expData['playerDataArray'][0]['capturedDieArray'][1]['properties'] = array("WasJustCaptured");
        $expData['playerDataArray'][0]['capturedDieArray'][1]['recipe'] = "(30)";
        $expData['playerDataArray'][0]['capturedDieArray'][1]['sides'] = 30;
        $expData['playerDataArray'][0]['capturedDieArray'][1]['value'] = 26;
        $expData['playerDataArray'][0]['optRequestArray'] = array();
        $expData['playerDataArray'][0]['roundScore'] = 57;
        $expData['playerDataArray'][0]['sideScore'] = 18;
        $expData['playerDataArray'][0]['waitingOnAction'] = false;
        $expData['playerDataArray'][1]['activeDieArray'][1]['value'] = 12;
        array_pop($expData['playerDataArray'][1]['activeDieArray']);
        $expData['playerDataArray'][1]['capturedDieArray'][0]['properties'] = array();
        $expData['playerDataArray'][1]['roundScore'] = 30;
        $expData['playerDataArray'][1]['sideScore'] = -18;
        $expData['playerDataArray'][1]['waitingOnAction'] = true;
        $expData['validAttackTypeArray'] = array("Power");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $_SESSION = $this->mock_test_user_login('responder004');
        $this->verify_api_submitTurn(
            array(30),
            'responder004 performed Power attack using [(30):20] against [k(8):1]; Defender k(8) was captured; Attacker (30) rerolled 20 => 30. ',
            $retval, array(array(1, 0), array(0, 1)),
            $gameId, 1, 'Power', 1, 0, '');
        $_SESSION = $this->mock_test_user_login('responder003');

        $expData['activePlayerIdx'] = 0;
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder004', 'message' => 'responder004 performed Power attack using [(30):20] against [k(8):1]; Defender k(8) was captured; Attacker (30) rerolled 20 => 30'));
        $expData['gameActionLogCount'] = 7;
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array();
        $expData['playerDataArray'][0]['activeDieArray'][1]['description'] = "Fire 13-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][1]['recipe'] = "F(13)";
        $expData['playerDataArray'][0]['activeDieArray'][1]['sides'] = 13;
        $expData['playerDataArray'][0]['activeDieArray'][1]['skills'] = array("Fire");
        $expData['playerDataArray'][0]['activeDieArray'][2]['description'] = "Stealth Y Swing Die (with 3 sides)";
        $expData['playerDataArray'][0]['activeDieArray'][2]['recipe'] = "d(Y)";
        $expData['playerDataArray'][0]['activeDieArray'][2]['sides'] = 3;
        $expData['playerDataArray'][0]['activeDieArray'][2]['skills'] = array("Stealth");
        array_pop($expData['playerDataArray'][0]['activeDieArray']);
        $expData['playerDataArray'][0]['capturedDieArray'][1]['properties'] = array();
        $expData['playerDataArray'][0]['roundScore'] = 53;
        $expData['playerDataArray'][0]['sideScore'] = 10;
        $expData['playerDataArray'][0]['waitingOnAction'] = true;
        $expData['playerDataArray'][1]['activeDieArray'][0]['value'] = 30;
        $expData['playerDataArray'][1]['capturedDieArray'][1]['properties'] = array("WasJustCaptured");
        $expData['playerDataArray'][1]['capturedDieArray'][1]['recipe'] = "k(8)";
        $expData['playerDataArray'][1]['capturedDieArray'][1]['sides'] = 8;
        $expData['playerDataArray'][1]['capturedDieArray'][1]['value'] = 1;
        $expData['playerDataArray'][1]['roundScore'] = 38;
        $expData['playerDataArray'][1]['sideScore'] = -10;
        $expData['playerDataArray'][1]['waitingOnAction'] = false;
        $expData['validAttackTypeArray'] = array("Power", "Skill");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_submitTurn(
            array(18, 3, 3),
            'responder003 performed Skill attack using [m(30):28,F(13):1,d(Y=3):1] against [(30):30]; Defender (30) was captured; Attacker m(30) remained the same size, rerolled 28 => 18; Attacker F(13) rerolled 1 => 3; Attacker d(Y=3) rerolled 1 => 3. ',
            $retval, array(array(0, 0), array(0, 1), array(0, 2), array(1, 0)),
            $gameId, 1, 'Skill', 0, 1, '');

        $expData['activePlayerIdx'] = 1;
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 performed Skill attack using [m(30):28,F(13):1,d(Y=3):1] against [(30):30]; Defender (30) was captured; Attacker m(30) remained the same size, rerolled 28 => 18; Attacker F(13) rerolled 1 => 3; Attacker d(Y=3) rerolled 1 => 3'));
        $expData['gameActionLogCount'] = 8;
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array("HasJustMorphed");
        $expData['playerDataArray'][0]['activeDieArray'][0]['value'] = 18;
        $expData['playerDataArray'][0]['activeDieArray'][1]['value'] = 3;
        $expData['playerDataArray'][0]['activeDieArray'][2]['value'] = 3;
        $expData['playerDataArray'][0]['capturedDieArray'][2]['properties'] = array("WasJustCaptured");
        $expData['playerDataArray'][0]['capturedDieArray'][2]['recipe'] = "(30)";
        $expData['playerDataArray'][0]['capturedDieArray'][2]['sides'] = 30;
        $expData['playerDataArray'][0]['capturedDieArray'][2]['value'] = 30;
        $expData['playerDataArray'][0]['roundScore'] = 83;
        $expData['playerDataArray'][0]['sideScore'] = 40;
        $expData['playerDataArray'][0]['waitingOnAction'] = false;
        $expData['playerDataArray'][1]['activeDieArray'][0]['value'] = 12;
        array_pop($expData['playerDataArray'][1]['activeDieArray']);
        $expData['playerDataArray'][1]['capturedDieArray'][1]['properties'] = array();
        $expData['playerDataArray'][1]['roundScore'] = 23;
        $expData['playerDataArray'][1]['sideScore'] = -40;
        $expData['playerDataArray'][1]['waitingOnAction'] = true;
        $expData['validAttackTypeArray'] = array("Power");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $_SESSION = $this->mock_test_user_login('responder004');
        $this->verify_api_submitTurn(
            array(4),
            'responder004 performed Power attack using [(30):12] against [F(13):3]; Defender F(13) was captured; Attacker (30) rerolled 12 => 4. ',
            $retval, array(array(1, 0), array(0, 1)),
            $gameId, 1, 'Power', 1, 0, '');
        $_SESSION = $this->mock_test_user_login('responder003');

        $expData['activePlayerIdx'] = 0;
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder004', 'message' => 'responder004 performed Power attack using [(30):12] against [F(13):3]; Defender F(13) was captured; Attacker (30) rerolled 12 => 4'));
        $expData['gameActionLogCount'] = 9;
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array();
        $expData['playerDataArray'][0]['activeDieArray'][1]['description'] = "Stealth Y Swing Die (with 3 sides)";
        $expData['playerDataArray'][0]['activeDieArray'][1]['recipe'] = "d(Y)";
        $expData['playerDataArray'][0]['activeDieArray'][1]['sides'] = 3;
        $expData['playerDataArray'][0]['activeDieArray'][1]['skills'] = array("Stealth");
        array_pop($expData['playerDataArray'][0]['activeDieArray']);
        $expData['playerDataArray'][0]['capturedDieArray'][2]['properties'] = array();
        $expData['playerDataArray'][0]['roundScore'] = 76.5;
        $expData['playerDataArray'][0]['sideScore'] = 27;
        $expData['playerDataArray'][0]['waitingOnAction'] = true;
        $expData['playerDataArray'][1]['activeDieArray'][0]['value'] = 4;
        $expData['playerDataArray'][1]['capturedDieArray'][2]['properties'] = array("WasJustCaptured");
        $expData['playerDataArray'][1]['capturedDieArray'][2]['recipe'] = "F(13)";
        $expData['playerDataArray'][1]['capturedDieArray'][2]['sides'] = 13;
        $expData['playerDataArray'][1]['capturedDieArray'][2]['value'] = 3;
        $expData['playerDataArray'][1]['roundScore'] = 36;
        $expData['playerDataArray'][1]['sideScore'] = -27;
        $expData['playerDataArray'][1]['waitingOnAction'] = false;

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_submitTurn(
            array(18, 3, 2, 5, 5, 2, 17, 13, 27),
            'responder003 performed Power attack using [m(30):18] against [(30):4]; Defender (30) was captured; Attacker m(30) remained the same size, rerolled 18 => 18. End of round: responder003 won round 1 (106.5 vs. 21). ',
            $retval, array(array(0, 0), array(1, 0)),
            $gameId, 1, 'Power', 0, 1, '');

        $expData['activePlayerIdx'] = null;
        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 performed Power attack using [m(30):18] against [(30):4]; Defender (30) was captured; Attacker m(30) remained the same size, rerolled 18 => 18'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'End of round: responder003 won round 1 (106.5 vs. 21)'));
        $expData['gameActionLogCount'] = 11;
        $expData['gameState'] = "SPECIFY_DICE";
        $expData['playerDataArray'][0]['activeDieArray'][0]['description'] = "Null 4-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][0]['recipe'] = "n(4)";
        $expData['playerDataArray'][0]['activeDieArray'][0]['sides'] = 4;
        $expData['playerDataArray'][0]['activeDieArray'][0]['skills'] = array("Null");
        $expData['playerDataArray'][0]['activeDieArray'][0]['value'] = null;
        $expData['playerDataArray'][0]['activeDieArray'][1]['description'] = "Morphing 5-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][1]['recipe'] = "m(5)";
        $expData['playerDataArray'][0]['activeDieArray'][1]['sides'] = 5;
        $expData['playerDataArray'][0]['activeDieArray'][1]['skills'] = array("Morphing");
        $expData['playerDataArray'][0]['activeDieArray'][1]['value'] = null;
        $expData['playerDataArray'][0]['activeDieArray'][2]['description'] = "Konstant 8-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][2]['properties'] = array();
        $expData['playerDataArray'][0]['activeDieArray'][2]['recipe'] = "k(8)";
        $expData['playerDataArray'][0]['activeDieArray'][2]['sides'] = 8;
        $expData['playerDataArray'][0]['activeDieArray'][2]['skills'] = array("Konstant");
        $expData['playerDataArray'][0]['activeDieArray'][2]['value'] = null;
        $expData['playerDataArray'][0]['activeDieArray'][3]['description'] = "Fire 13-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][3]['properties'] = array();
        $expData['playerDataArray'][0]['activeDieArray'][3]['recipe'] = "F(13)";
        $expData['playerDataArray'][0]['activeDieArray'][3]['sides'] = 13;
        $expData['playerDataArray'][0]['activeDieArray'][3]['skills'] = array("Fire");
        $expData['playerDataArray'][0]['activeDieArray'][3]['value'] = null;
        $expData['playerDataArray'][0]['activeDieArray'][4]['description'] = "Stealth Y Swing Die (with 3 sides)";
        $expData['playerDataArray'][0]['activeDieArray'][4]['properties'] = array();
        $expData['playerDataArray'][0]['activeDieArray'][4]['recipe'] = "d(Y)";
        $expData['playerDataArray'][0]['activeDieArray'][4]['sides'] = 3;
        $expData['playerDataArray'][0]['activeDieArray'][4]['skills'] = array("Stealth");
        $expData['playerDataArray'][0]['activeDieArray'][4]['value'] = null;
        array_pop($expData['playerDataArray'][0]['capturedDieArray']);
        array_pop($expData['playerDataArray'][0]['capturedDieArray']);
        array_pop($expData['playerDataArray'][0]['capturedDieArray']);
        $expData['playerDataArray'][0]['gameScoreArray'] = array("D" => 0, "L" => 0, "W" => 1);
        $expData['playerDataArray'][0]['prevSwingValueArray'] = array("Y" => 3);
        $expData['playerDataArray'][0]['roundScore'] = null;
        $expData['playerDataArray'][0]['sideScore'] = null;
        $expData['playerDataArray'][0]['waitingOnAction'] = false;
        $expData['playerDataArray'][1]['activeDieArray'][0]['value'] = null;
        $expData['playerDataArray'][1]['activeDieArray'][1]['description'] = "30-sided die";
        $expData['playerDataArray'][1]['activeDieArray'][1]['properties'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][1]['recipe'] = "(30)";
        $expData['playerDataArray'][1]['activeDieArray'][1]['sides'] = 30;
        $expData['playerDataArray'][1]['activeDieArray'][1]['skills'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][1]['value'] = null;
        $expData['playerDataArray'][1]['activeDieArray'][2]['description'] = "30-sided die";
        $expData['playerDataArray'][1]['activeDieArray'][2]['properties'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][2]['recipe'] = "(30)";
        $expData['playerDataArray'][1]['activeDieArray'][2]['sides'] = 30;
        $expData['playerDataArray'][1]['activeDieArray'][2]['skills'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][2]['value'] = null;
        $expData['playerDataArray'][1]['activeDieArray'][3]['description'] = "Option Die (with 6 or 30 sides)";
        $expData['playerDataArray'][1]['activeDieArray'][3]['properties'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][3]['recipe'] = "(6/30)";
        $expData['playerDataArray'][1]['activeDieArray'][3]['sides'] = null;
        $expData['playerDataArray'][1]['activeDieArray'][3]['skills'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][3]['value'] = null;
        array_pop($expData['playerDataArray'][1]['capturedDieArray']);
        array_pop($expData['playerDataArray'][1]['capturedDieArray']);
        array_pop($expData['playerDataArray'][1]['capturedDieArray']);
        $expData['playerDataArray'][1]['gameScoreArray'] = array("D" => 0, "L" => 1, "W" => 0);
        $expData['playerDataArray'][1]['optRequestArray'] = array("3" => array(6, 30));
        $expData['playerDataArray'][1]['prevOptValueArray'] = array("3" => 30);
        $expData['playerDataArray'][1]['roundScore'] = null;
        $expData['playerDataArray'][1]['sideScore'] = null;
        $expData['playerDataArray'][1]['waitingOnAction'] = true;
        $expData['roundNumber'] = 2;
        $expData['validAttackTypeArray'] = array();

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $_SESSION = $this->mock_test_user_login('responder004');
        $this->verify_api_submitDieValues(
            array(26),
            $gameId, 2, NULL, array(3 => 30));
        $_SESSION = $this->mock_test_user_login('responder003');

        $expData['activePlayerIdx'] = 0;
        array_pop($expData['gameActionLog']);
        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder004', 'message' => 'responder004 set option dice: (6/30=30)'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => '', 'message' => 'responder003 won initiative for round 2. Initial die values: responder003 rolled [n(4):3, m(5):2, k(8):5, F(13):5, d(Y=3):2], responder004 rolled [(30):17, (30):13, (30):27, (6/30=30):26].'));
        $expData['gameActionLogCount'] = 13;
        $expData['gameState'] = "START_TURN";
        $expData['playerDataArray'][0]['activeDieArray'][0]['value'] = 3;
        $expData['playerDataArray'][0]['activeDieArray'][1]['value'] = 2;
        $expData['playerDataArray'][0]['activeDieArray'][2]['value'] = 5;
        $expData['playerDataArray'][0]['activeDieArray'][3]['value'] = 5;
        $expData['playerDataArray'][0]['activeDieArray'][4]['value'] = 2;
        $expData['playerDataArray'][0]['prevSwingValueArray'] = array();
        $expData['playerDataArray'][0]['roundScore'] = 14.5;
        $expData['playerDataArray'][0]['sideScore'] = -30.3;
        $expData['playerDataArray'][0]['waitingOnAction'] = true;
        $expData['playerDataArray'][1]['activeDieArray'][0]['value'] = 17;
        $expData['playerDataArray'][1]['activeDieArray'][1]['value'] = 13;
        $expData['playerDataArray'][1]['activeDieArray'][2]['value'] = 27;
        $expData['playerDataArray'][1]['activeDieArray'][3]['description'] = "Option Die (with 30 sides)";
        $expData['playerDataArray'][1]['activeDieArray'][3]['sides'] = 30;
        $expData['playerDataArray'][1]['activeDieArray'][3]['value'] = 26;
        $expData['playerDataArray'][1]['prevOptValueArray'] = array();
        $expData['playerDataArray'][1]['roundScore'] = 60;
        $expData['playerDataArray'][1]['sideScore'] = 30.3;
        $expData['playerDataArray'][1]['waitingOnAction'] = false;
        $expData['validAttackTypeArray'] = array("Skill");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_submitTurn(
            array(),
            'responder003 chose to perform a Skill attack using [n(4):3,m(5):2,k(8):5,d(Y=3):2] against [(30):13]; responder003 must turn down fire dice to complete this attack. ',
            $retval, array(array(0, 0), array(0, 1), array(0, 2), array(0, 4), array(1, 1)),
            $gameId, 2, 'Skill', 0, 1, '');

        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 chose to perform a Skill attack using [n(4):3,m(5):2,k(8):5,d(Y=3):2] against [(30):13]; responder003 must turn down fire dice to complete this attack'));
        $expData['gameActionLogCount'] = 14;
        $expData['gameState'] = "ADJUST_FIRE_DICE";
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array("IsAttacker");
        $expData['playerDataArray'][0]['activeDieArray'][1]['properties'] = array("IsAttacker");
        $expData['playerDataArray'][0]['activeDieArray'][2]['properties'] = array("IsAttacker");
        $expData['playerDataArray'][0]['activeDieArray'][4]['properties'] = array("IsAttacker");
        $expData['playerDataArray'][1]['activeDieArray'][1]['properties'] = array("IsAttackTarget");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_adjustFire(
            array(1, 4, 2),
            'responder003 turned down fire dice: F(13) from 5 to 4; Defender (30) recipe changed to n(30), was captured; Attacker n(4) rerolled 3 => 1; Attacker m(5) changed size from 5 to 30 sides, recipe changed from m(5) to m(30), rerolled 2 => 4; Attacker k(8) does not reroll; Attacker d(Y=3) rerolled 2 => 2. ',
            $retval, $gameId, 2, 'turndown', array(3), array('4'));

        $expData['activePlayerIdx'] = 1;
        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 turned down fire dice: F(13) from 5 to 4; Defender (30) recipe changed to n(30), was captured; Attacker n(4) rerolled 3 => 1; Attacker m(5) changed size from 5 to 30 sides, recipe changed from m(5) to m(30), rerolled 2 => 4; Attacker k(8) does not reroll; Attacker d(Y=3) rerolled 2 => 2'));
        $expData['gameActionLogCount'] = 15;
        $expData['gameState'] = "START_TURN";
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array();
        $expData['playerDataArray'][0]['activeDieArray'][0]['value'] = 1;
        $expData['playerDataArray'][0]['activeDieArray'][1]['description'] = "Morphing 30-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][1]['properties'] = array("HasJustMorphed");
        $expData['playerDataArray'][0]['activeDieArray'][1]['recipe'] = "m(30)";
        $expData['playerDataArray'][0]['activeDieArray'][1]['sides'] = 30;
        $expData['playerDataArray'][0]['activeDieArray'][1]['value'] = 4;
        $expData['playerDataArray'][0]['activeDieArray'][2]['properties'] = array();
        $expData['playerDataArray'][0]['activeDieArray'][3]['value'] = 4;
        $expData['playerDataArray'][0]['activeDieArray'][4]['properties'] = array();
        $expData['playerDataArray'][0]['capturedDieArray'][0]['properties'] = array("WasJustCaptured");
        $expData['playerDataArray'][0]['capturedDieArray'][0]['recipe'] = "n(30)";
        $expData['playerDataArray'][0]['capturedDieArray'][0]['sides'] = 30;
        $expData['playerDataArray'][0]['capturedDieArray'][0]['value'] = 13;
        $expData['playerDataArray'][0]['roundScore'] = 27;
        $expData['playerDataArray'][0]['sideScore'] = -12;
        $expData['playerDataArray'][0]['waitingOnAction'] = false;
        $expData['playerDataArray'][1]['activeDieArray'][1]['properties'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][1]['value'] = 27;
        $expData['playerDataArray'][1]['activeDieArray'][2]['description'] = "Option Die (with 30 sides)";
        $expData['playerDataArray'][1]['activeDieArray'][2]['recipe'] = "(6/30)";
        $expData['playerDataArray'][1]['activeDieArray'][2]['value'] = 26;
        array_pop($expData['playerDataArray'][1]['activeDieArray']);
        $expData['playerDataArray'][1]['optRequestArray'] = array("2" => array(6, 30));
        $expData['playerDataArray'][1]['roundScore'] = 45;
        $expData['playerDataArray'][1]['sideScore'] = 12;
        $expData['playerDataArray'][1]['waitingOnAction'] = true;
        $expData['validAttackTypeArray'] = array("Power");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $_SESSION = $this->mock_test_user_login('responder004');
        $this->verify_api_submitTurn(
            array(2),
            'responder004 performed Power attack using [(6/30=30):26] against [k(8):5]; Defender k(8) was captured; Attacker (6/30=30) rerolled 26 => 2. ',
            $retval, array(array(1, 2), array(0, 2)),
            $gameId, 2, 'Power', 1, 0, '');
        $_SESSION = $this->mock_test_user_login('responder003');

        $expData['activePlayerIdx'] = 0;
        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder004', 'message' => 'responder004 performed Power attack using [(6/30=30):26] against [k(8):5]; Defender k(8) was captured; Attacker (6/30=30) rerolled 26 => 2'));
        $expData['gameActionLogCount'] = 16;
        $expData['playerDataArray'][0]['activeDieArray'][1]['properties'] = array();
        $expData['playerDataArray'][0]['activeDieArray'][2]['description'] = "Fire 13-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][2]['recipe'] = "F(13)";
        $expData['playerDataArray'][0]['activeDieArray'][2]['sides'] = 13;
        $expData['playerDataArray'][0]['activeDieArray'][2]['skills'] = array("Fire");
        $expData['playerDataArray'][0]['activeDieArray'][2]['value'] = 4;
        $expData['playerDataArray'][0]['activeDieArray'][3]['description'] = "Stealth Y Swing Die (with 3 sides)";
        $expData['playerDataArray'][0]['activeDieArray'][3]['recipe'] = "d(Y)";
        $expData['playerDataArray'][0]['activeDieArray'][3]['sides'] = 3;
        $expData['playerDataArray'][0]['activeDieArray'][3]['skills'] = array("Stealth");
        $expData['playerDataArray'][0]['activeDieArray'][3]['value'] = 2;
        array_pop($expData['playerDataArray'][0]['activeDieArray']);
        $expData['playerDataArray'][0]['capturedDieArray'][0]['properties'] = array();
        $expData['playerDataArray'][0]['roundScore'] = 23;
        $expData['playerDataArray'][0]['sideScore'] = -20;
        $expData['playerDataArray'][0]['waitingOnAction'] = true;
        $expData['playerDataArray'][1]['activeDieArray'][2]['value'] = 2;
        $expData['playerDataArray'][1]['capturedDieArray'][0]['properties'] = array("WasJustCaptured");
        $expData['playerDataArray'][1]['capturedDieArray'][0]['recipe'] = "k(8)";
        $expData['playerDataArray'][1]['capturedDieArray'][0]['sides'] = 8;
        $expData['playerDataArray'][1]['capturedDieArray'][0]['value'] = 5;
        $expData['playerDataArray'][1]['roundScore'] = 53;
        $expData['playerDataArray'][1]['sideScore'] = 20;
        $expData['playerDataArray'][1]['waitingOnAction'] = false;
        $expData['validAttackTypeArray'] = array("Power", "Skill");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_submitTurn(
            array(),
            'responder003 chose to perform a Skill attack using [n(4):1] against [(6/30=30):2]; responder003 must turn down fire dice to complete this attack. ',
            $retval, array(array(0, 0), array(1, 2)),
            $gameId, 2, 'Skill', 0, 1, '');

        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 chose to perform a Skill attack using [n(4):1] against [(6/30=30):2]; responder003 must turn down fire dice to complete this attack'));
        $expData['gameActionLogCount'] = 17;
        $expData['gameState'] = "ADJUST_FIRE_DICE";
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array("IsAttacker");
        $expData['playerDataArray'][1]['activeDieArray'][2]['properties'] = array("IsAttackTarget");
        $expData['validAttackTypeArray'] = array("Skill");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_adjustFire(
            array(),
            'responder003 chose to abandon this attack and start over. ',
            $retval, $gameId, 2, 'cancel', array(), array());

        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 chose to abandon this attack and start over'));
        $expData['gameActionLogCount'] = 18;
        $expData['gameState'] = "START_TURN";
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][2]['properties'] = array();
        $expData['validAttackTypeArray'] = array("Power", "Skill");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_submitTurn(
            array(),
            'responder003 chose to perform a Skill attack using [n(4):1] against [(6/30=30):2]; responder003 must turn down fire dice to complete this attack. ',
            $retval, array(array(0, 0), array(1, 2)),
            $gameId, 2, 'Skill', 0, 1, '');

        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 chose to perform a Skill attack using [n(4):1] against [(6/30=30):2]; responder003 must turn down fire dice to complete this attack'));
        $expData['gameActionLogCount'] = 19;
        $expData['gameState'] = "ADJUST_FIRE_DICE";
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array("IsAttacker");
        $expData['playerDataArray'][1]['activeDieArray'][2]['properties'] = array("IsAttackTarget");
        $expData['validAttackTypeArray'] = array("Skill");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_adjustFire(
            array(),
            'responder003 chose to abandon this attack and start over. ',
            $retval, $gameId, 2, 'cancel', array(), array());

        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 chose to abandon this attack and start over'));
        $expData['gameActionLogCount'] = 20;
        $expData['gameState'] = "START_TURN";
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][2]['properties'] = array();
        $expData['validAttackTypeArray'] = array("Power", "Skill");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_submitTurn(
            array(),
            'responder003 chose to perform a Skill attack using [n(4):1] against [(6/30=30):2]; responder003 must turn down fire dice to complete this attack. ',
            $retval, array(array(0, 0), array(1, 2)),
            $gameId, 2, 'Skill', 0, 1, '');

        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 chose to perform a Skill attack using [n(4):1] against [(6/30=30):2]; responder003 must turn down fire dice to complete this attack'));
        $expData['gameActionLogCount'] = 21;
        $expData['gameState'] = "ADJUST_FIRE_DICE";
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array("IsAttacker");
        $expData['playerDataArray'][1]['activeDieArray'][2]['properties'] = array("IsAttackTarget");
        $expData['validAttackTypeArray'] = array("Skill");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_adjustFire(
            array(),
            'responder003 chose to abandon this attack and start over. ',
            $retval, $gameId, 2, 'cancel', array(), array());

        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 chose to abandon this attack and start over'));
        $expData['gameActionLogCount'] = 22;
        $expData['gameState'] = "START_TURN";
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][2]['properties'] = array();
        $expData['validAttackTypeArray'] = array("Power", "Skill");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_submitTurn(
            array(),
            'responder003 chose to perform a Power attack using [n(4):1] against [(6/30=30):2]; responder003 must turn down fire dice to complete this attack. ',
            $retval, array(array(0, 0), array(1, 2)),
            $gameId, 2, 'Power', 0, 1, '');

        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 chose to perform a Power attack using [n(4):1] against [(6/30=30):2]; responder003 must turn down fire dice to complete this attack'));
        $expData['gameActionLogCount'] = 23;
        $expData['gameState'] = "ADJUST_FIRE_DICE";
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array("IsAttacker");
        $expData['playerDataArray'][1]['activeDieArray'][2]['properties'] = array("IsAttackTarget");
        $expData['validAttackTypeArray'] = array("Power");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_adjustFire(
            array(3),
            'responder003 turned down fire dice: F(13) from 4 to 2; Defender (6/30=30) recipe changed to n(6/30=30), was captured; Attacker n(4) rerolled 1 => 3. ',
            $retval, $gameId, 2, 'turndown', array(2), array('2'));

        $expData['activePlayerIdx'] = 1;
        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 turned down fire dice: F(13) from 4 to 2; Defender (6/30=30) recipe changed to n(6/30=30), was captured; Attacker n(4) rerolled 1 => 3'));
        $expData['gameActionLogCount'] = 24;
        $expData['gameState'] = "START_TURN";
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array();
        $expData['playerDataArray'][0]['activeDieArray'][0]['value'] = 3;
        $expData['playerDataArray'][0]['activeDieArray'][2]['value'] = 2;
        $expData['playerDataArray'][0]['capturedDieArray'][1]['properties'] = array("WasJustCaptured");
        $expData['playerDataArray'][0]['capturedDieArray'][1]['recipe'] = "n(6/30)";
        $expData['playerDataArray'][0]['capturedDieArray'][1]['sides'] = 30;
        $expData['playerDataArray'][0]['capturedDieArray'][1]['value'] = 2;
        $expData['playerDataArray'][0]['sideScore'] = -10;
        $expData['playerDataArray'][0]['waitingOnAction'] = false;
        array_pop($expData['playerDataArray'][1]['activeDieArray']);
        $expData['playerDataArray'][1]['capturedDieArray'][0]['properties'] = array();
        $expData['playerDataArray'][1]['optRequestArray'] = array();
        $expData['playerDataArray'][1]['roundScore'] = 38;
        $expData['playerDataArray'][1]['sideScore'] = 10;
        $expData['playerDataArray'][1]['waitingOnAction'] = true;

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $_SESSION = $this->mock_test_user_login('responder004');
        $this->verify_api_submitTurn(
            array(5),
            'responder004 performed Power attack using [(30):17] against [F(13):2]; Defender F(13) was captured; Attacker (30) rerolled 17 => 5. ',
            $retval, array(array(1, 0), array(0, 2)),
            $gameId, 2, 'Power', 1, 0, '');
        $_SESSION = $this->mock_test_user_login('responder003');

        $expData['activePlayerIdx'] = 0;
        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder004', 'message' => 'responder004 performed Power attack using [(30):17] against [F(13):2]; Defender F(13) was captured; Attacker (30) rerolled 17 => 5'));
        $expData['gameActionLogCount'] = 25;
        $expData['playerDataArray'][0]['activeDieArray'][2]['description'] = "Stealth Y Swing Die (with 3 sides)";
        $expData['playerDataArray'][0]['activeDieArray'][2]['recipe'] = "d(Y)";
        $expData['playerDataArray'][0]['activeDieArray'][2]['sides'] = 3;
        $expData['playerDataArray'][0]['activeDieArray'][2]['skills'] = array("Stealth");
        array_pop($expData['playerDataArray'][0]['activeDieArray']);
        $expData['playerDataArray'][0]['capturedDieArray'][1]['properties'] = array();
        $expData['playerDataArray'][0]['roundScore'] = 16.5;
        $expData['playerDataArray'][0]['sideScore'] = -23;
        $expData['playerDataArray'][0]['waitingOnAction'] = true;
        $expData['playerDataArray'][1]['activeDieArray'][0]['value'] = 5;
        $expData['playerDataArray'][1]['capturedDieArray'][1]['properties'] = array("WasJustCaptured");
        $expData['playerDataArray'][1]['capturedDieArray'][1]['recipe'] = "F(13)";
        $expData['playerDataArray'][1]['capturedDieArray'][1]['sides'] = 13;
        $expData['playerDataArray'][1]['capturedDieArray'][1]['value'] = 2;
        $expData['playerDataArray'][1]['roundScore'] = 51;
        $expData['playerDataArray'][1]['sideScore'] = 23;
        $expData['playerDataArray'][1]['waitingOnAction'] = false;
        $expData['validAttackTypeArray'] = array("Skill");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_submitTurn(
            array(2, 2),
            'responder003 performed Skill attack using [n(4):3,d(Y=3):2] against [(30):5]; Defender (30) recipe changed to n(30), was captured; Attacker n(4) rerolled 3 => 2; Attacker d(Y=3) rerolled 2 => 2. ',
            $retval, array(array(0, 0), array(0, 2), array(1, 0)),
            $gameId, 2, 'Skill', 0, 1, '');

        $expData['activePlayerIdx'] = 1;
        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 performed Skill attack using [n(4):3,d(Y=3):2] against [(30):5]; Defender (30) recipe changed to n(30), was captured; Attacker n(4) rerolled 3 => 2; Attacker d(Y=3) rerolled 2 => 2'));
        $expData['gameActionLogCount'] = 26;
        $expData['playerDataArray'][0]['activeDieArray'][0]['value'] = 2;
        $expData['playerDataArray'][0]['capturedDieArray'][2]['properties'] = array("WasJustCaptured");
        $expData['playerDataArray'][0]['capturedDieArray'][2]['recipe'] = "n(30)";
        $expData['playerDataArray'][0]['capturedDieArray'][2]['sides'] = 30;
        $expData['playerDataArray'][0]['capturedDieArray'][2]['value'] = 5;
        $expData['playerDataArray'][0]['sideScore'] = -13;
        $expData['playerDataArray'][0]['waitingOnAction'] = false;
        $expData['playerDataArray'][1]['activeDieArray'][0]['value'] = 27;
        array_pop($expData['playerDataArray'][1]['activeDieArray']);
        $expData['playerDataArray'][1]['capturedDieArray'][1]['properties'] = array();
        $expData['playerDataArray'][1]['roundScore'] = 36;
        $expData['playerDataArray'][1]['sideScore'] = 13;
        $expData['playerDataArray'][1]['waitingOnAction'] = true;
        $expData['validAttackTypeArray'] = array("Power");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $_SESSION = $this->mock_test_user_login('responder004');
        $this->verify_api_submitTurn(
            array(21),
            'responder004 performed Power attack using [(30):27] against [n(4):2]; Defender n(4) was captured; Attacker (30) rerolled 27 => 21. responder003 passed. ',
            $retval, array(array(1, 0), array(0, 0)),
            $gameId, 2, 'Power', 1, 0, '');
        $_SESSION = $this->mock_test_user_login('responder003');

        $expData['gameActionLog'] = array();
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 chose to perform a Skill attack using [n(4):1] against [(6/30=30):2]; responder003 must turn down fire dice to complete this attack'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 chose to abandon this attack and start over'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 chose to perform a Skill attack using [n(4):1] against [(6/30=30):2]; responder003 must turn down fire dice to complete this attack'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 chose to abandon this attack and start over'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 chose to perform a Power attack using [n(4):1] against [(6/30=30):2]; responder003 must turn down fire dice to complete this attack'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 turned down fire dice: F(13) from 4 to 2; Defender (6/30=30) recipe changed to n(6/30=30), was captured; Attacker n(4) rerolled 1 => 3'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder004', 'message' => 'responder004 performed Power attack using [(30):17] against [F(13):2]; Defender F(13) was captured; Attacker (30) rerolled 17 => 5'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 performed Skill attack using [n(4):3,d(Y=3):2] against [(30):5]; Defender (30) recipe changed to n(30), was captured; Attacker n(4) rerolled 3 => 2; Attacker d(Y=3) rerolled 2 => 2'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder004', 'message' => 'responder004 performed Power attack using [(30):27] against [n(4):2]; Defender n(4) was captured; Attacker (30) rerolled 27 => 21'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 passed'));
        $expData['gameActionLogCount'] = 28;
        $expData['playerDataArray'][0]['activeDieArray'][0]['description'] = "Morphing 30-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][0]['recipe'] = "m(30)";
        $expData['playerDataArray'][0]['activeDieArray'][0]['sides'] = 30;
        $expData['playerDataArray'][0]['activeDieArray'][0]['skills'] = array("Morphing");
        $expData['playerDataArray'][0]['activeDieArray'][0]['value'] = 4;
        $expData['playerDataArray'][0]['activeDieArray'][1]['description'] = "Stealth Y Swing Die (with 3 sides)";
        $expData['playerDataArray'][0]['activeDieArray'][1]['recipe'] = "d(Y)";
        $expData['playerDataArray'][0]['activeDieArray'][1]['sides'] = 3;
        $expData['playerDataArray'][0]['activeDieArray'][1]['skills'] = array("Stealth");
        $expData['playerDataArray'][0]['activeDieArray'][1]['value'] = 2;
        array_pop($expData['playerDataArray'][0]['activeDieArray']);
        $expData['playerDataArray'][0]['capturedDieArray'][2]['properties'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][0]['value'] = 21;
        $expData['playerDataArray'][1]['capturedDieArray'][2]['properties'] = array();
        $expData['playerDataArray'][1]['capturedDieArray'][2]['recipe'] = "n(4)";
        $expData['playerDataArray'][1]['capturedDieArray'][2]['sides'] = 4;
        $expData['playerDataArray'][1]['capturedDieArray'][2]['value'] = 2;

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $_SESSION = $this->mock_test_user_login('responder004');
        $this->verify_api_submitTurn(
            array(25, 3, 1, 6, 11, 11, 12, 15, 12),
            'responder004 performed Power attack using [(30):21] against [m(30):4]; Defender m(30) was captured; Attacker (30) rerolled 21 => 25. responder003 passed. responder004 passed. End of round: responder004 won round 2 (66 vs. 1.5). ',
            $retval, array(array(1, 0), array(0, 0)),
            $gameId, 2, 'Power', 1, 0, '');
        $_SESSION = $this->mock_test_user_login('responder003');

        $expData['activePlayerIdx'] = null;
        array_pop($expData['gameActionLog']);
        array_pop($expData['gameActionLog']);
        array_pop($expData['gameActionLog']);
        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder004', 'message' => 'responder004 performed Power attack using [(30):21] against [m(30):4]; Defender m(30) was captured; Attacker (30) rerolled 21 => 25'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 passed'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder004', 'message' => 'responder004 passed'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder004', 'message' => 'End of round: responder004 won round 2 (66 vs. 1.5)'));
        $expData['gameActionLogCount'] = 32;
        $expData['gameState'] = "SPECIFY_DICE";
        $expData['playerDataArray'][0]['activeDieArray'][0]['description'] = "Null 4-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][0]['recipe'] = "n(4)";
        $expData['playerDataArray'][0]['activeDieArray'][0]['sides'] = 4;
        $expData['playerDataArray'][0]['activeDieArray'][0]['skills'] = array("Null");
        $expData['playerDataArray'][0]['activeDieArray'][0]['value'] = null;
        $expData['playerDataArray'][0]['activeDieArray'][1]['description'] = "Morphing 5-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][1]['recipe'] = "m(5)";
        $expData['playerDataArray'][0]['activeDieArray'][1]['sides'] = 5;
        $expData['playerDataArray'][0]['activeDieArray'][1]['skills'] = array("Morphing");
        $expData['playerDataArray'][0]['activeDieArray'][1]['value'] = null;
        $expData['playerDataArray'][0]['activeDieArray'][2]['description'] = "Konstant 8-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][2]['properties'] = array();
        $expData['playerDataArray'][0]['activeDieArray'][2]['recipe'] = "k(8)";
        $expData['playerDataArray'][0]['activeDieArray'][2]['sides'] = 8;
        $expData['playerDataArray'][0]['activeDieArray'][2]['skills'] = array("Konstant");
        $expData['playerDataArray'][0]['activeDieArray'][2]['value'] = null;
        $expData['playerDataArray'][0]['activeDieArray'][3]['description'] = "Fire 13-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][3]['properties'] = array();
        $expData['playerDataArray'][0]['activeDieArray'][3]['recipe'] = "F(13)";
        $expData['playerDataArray'][0]['activeDieArray'][3]['sides'] = 13;
        $expData['playerDataArray'][0]['activeDieArray'][3]['skills'] = array("Fire");
        $expData['playerDataArray'][0]['activeDieArray'][3]['value'] = null;
        $expData['playerDataArray'][0]['activeDieArray'][4]['description'] = "Stealth Y Swing Die";
        $expData['playerDataArray'][0]['activeDieArray'][4]['properties'] = array();
        $expData['playerDataArray'][0]['activeDieArray'][4]['recipe'] = "d(Y)";
        $expData['playerDataArray'][0]['activeDieArray'][4]['sides'] = null;
        $expData['playerDataArray'][0]['activeDieArray'][4]['skills'] = array("Stealth");
        $expData['playerDataArray'][0]['activeDieArray'][4]['value'] = null;
        array_pop($expData['playerDataArray'][0]['capturedDieArray']);
        array_pop($expData['playerDataArray'][0]['capturedDieArray']);
        array_pop($expData['playerDataArray'][0]['capturedDieArray']);
        $expData['playerDataArray'][0]['gameScoreArray'] = array("D" => 0, "L" => 1, "W" => 1);
        $expData['playerDataArray'][0]['prevSwingValueArray'] = array("Y" => 3);
        $expData['playerDataArray'][0]['roundScore'] = null;
        $expData['playerDataArray'][0]['sideScore'] = null;
        $expData['playerDataArray'][0]['waitingOnAction'] = true;
        $expData['playerDataArray'][1]['activeDieArray'][0]['value'] = null;
        $expData['playerDataArray'][1]['activeDieArray'][1]['description'] = "30-sided die";
        $expData['playerDataArray'][1]['activeDieArray'][1]['properties'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][1]['recipe'] = "(30)";
        $expData['playerDataArray'][1]['activeDieArray'][1]['sides'] = 30;
        $expData['playerDataArray'][1]['activeDieArray'][1]['skills'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][1]['value'] = null;
        $expData['playerDataArray'][1]['activeDieArray'][2]['description'] = "30-sided die";
        $expData['playerDataArray'][1]['activeDieArray'][2]['properties'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][2]['recipe'] = "(30)";
        $expData['playerDataArray'][1]['activeDieArray'][2]['sides'] = 30;
        $expData['playerDataArray'][1]['activeDieArray'][2]['skills'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][2]['value'] = null;
        $expData['playerDataArray'][1]['activeDieArray'][3]['description'] = "Option Die (with 30 sides)";
        $expData['playerDataArray'][1]['activeDieArray'][3]['properties'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][3]['recipe'] = "(6/30)";
        $expData['playerDataArray'][1]['activeDieArray'][3]['sides'] = 30;
        $expData['playerDataArray'][1]['activeDieArray'][3]['skills'] = array();
        $expData['playerDataArray'][1]['activeDieArray'][3]['value'] = null;
        array_pop($expData['playerDataArray'][1]['capturedDieArray']);
        array_pop($expData['playerDataArray'][1]['capturedDieArray']);
        array_pop($expData['playerDataArray'][1]['capturedDieArray']);
        $expData['playerDataArray'][1]['gameScoreArray'] = array("D" => 0, "L" => 1, "W" => 1);
        $expData['playerDataArray'][1]['optRequestArray'] = array("3" => array(6, 30));
        $expData['playerDataArray'][1]['prevOptValueArray'] = array("3" => 30);
        $expData['playerDataArray'][1]['roundScore'] = null;
        $expData['playerDataArray'][1]['sideScore'] = null;
        $expData['playerDataArray'][1]['waitingOnAction'] = false;
        $expData['roundNumber'] = 3;
        $expData['validAttackTypeArray'] = array();

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_submitDieValues(
            array(4),
            $gameId, 3, array('Y' => 6), NULL);

        $expData['activePlayerIdx'] = 0;
        array_pop($expData['gameActionLog']);
        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 set swing values: Y=6'));
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => '', 'message' => 'responder003 won initiative for round 3. Initial die values: responder003 rolled [n(4):3, m(5):1, k(8):6, F(13):11, d(Y=6):4], responder004 rolled [(30):11, (30):12, (30):15, (6/30=30):12].'));
        $expData['gameActionLogCount'] = 34;
        $expData['gameState'] = "START_TURN";
        $expData['playerDataArray'][0]['activeDieArray'][0]['value'] = 3;
        $expData['playerDataArray'][0]['activeDieArray'][1]['value'] = 1;
        $expData['playerDataArray'][0]['activeDieArray'][2]['value'] = 6;
        $expData['playerDataArray'][0]['activeDieArray'][3]['value'] = 11;
        $expData['playerDataArray'][0]['activeDieArray'][4]['description'] = "Stealth Y Swing Die (with 6 sides)";
        $expData['playerDataArray'][0]['activeDieArray'][4]['sides'] = 6;
        $expData['playerDataArray'][0]['activeDieArray'][4]['value'] = 4;
        $expData['playerDataArray'][0]['prevSwingValueArray'] = array();
        $expData['playerDataArray'][0]['roundScore'] = 16;
        $expData['playerDataArray'][0]['sideScore'] = -29.3;
        $expData['playerDataArray'][1]['activeDieArray'][0]['value'] = 11;
        $expData['playerDataArray'][1]['activeDieArray'][1]['value'] = 12;
        $expData['playerDataArray'][1]['activeDieArray'][2]['value'] = 15;
        $expData['playerDataArray'][1]['activeDieArray'][3]['value'] = 12;
        $expData['playerDataArray'][1]['prevOptValueArray'] = array();
        $expData['playerDataArray'][1]['roundScore'] = 60;
        $expData['playerDataArray'][1]['sideScore'] = 29.3;
        $expData['validAttackTypeArray'] = array("Skill");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        $this->verify_api_submitTurn(
            array(),
            'responder003 chose to perform a Skill attack using [n(4):3,m(5):1,k(8):6,d(Y=6):4] against [(30):11]; responder003 must turn down fire dice to complete this attack. ',
            $retval, array(array(0, 0), array(0, 1), array(0, 2), array(0, 4), array(1, 0)),
            $gameId, 3, 'Skill', 0, 1, '');

        array_pop($expData['gameActionLog']);
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 chose to perform a Skill attack using [n(4):3,m(5):1,k(8):6,d(Y=6):4] against [(30):11]; responder003 must turn down fire dice to complete this attack'));
        $expData['gameActionLogCount'] = 35;
        $expData['gameState'] = "ADJUST_FIRE_DICE";
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array("IsAttacker");
        $expData['playerDataArray'][0]['activeDieArray'][1]['properties'] = array("IsAttacker");
        $expData['playerDataArray'][0]['activeDieArray'][2]['properties'] = array("IsAttacker");
        $expData['playerDataArray'][0]['activeDieArray'][4]['properties'] = array("IsAttacker");
        $expData['playerDataArray'][1]['activeDieArray'][0]['properties'] = array("IsAttackTarget");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);


        $this->verify_api_adjustFire(
            array(2, 4, 2),
            'responder003 turned down fire dice: F(13) from 11 to 2; Defender (30) recipe changed to n(30), was captured; Attacker n(4) rerolled 3 => 2; Attacker m(5) changed size from 5 to 30 sides, recipe changed from m(5) to m(30), rerolled 1 => 4; Attacker k(8) does not reroll; Attacker d(Y=6) rerolled 4 => 2. ',
            $retval, $gameId, 3, 'turndown', array(3), array('2'));
    }
```

**Comment by cgolubi1** [comment]
Per discussion on IRC, let's merge this now on the theory that it's an improvement over the current behavior and i didn't see any internal errors or obvious regressions.  Shadowshade will create new issues for the UI and logic issues i found in the Fk case.
